### ISSUE TITLE
BUAS koppeling

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/ppp#11]
Pure

Lijkt sterk op de Pure v2 API, maar BUAS gebruikt Pure v1.

**Comment by fako** [comment]
Punten die opvallen voor persons:
- [ ] Geen ISNI?

**Comment by fako** [comment]
Niet helemaal duidelijk hoe we "participants" tegenover "collaborators" moeten duiden. Ik zal daar een email over sturen

**Comment by fako** [comment]
Alles wat ontbreekt bij personen voor HvA ontbreekt ook hier: https://github.com/nppo/ppp/issues/9
Wat extra onbreekt is de ISNI.

**Comment by fako** [comment]
Er zit ook nog HTML in de description @JohnMeurs. Kan dit wel of geen kwaad voor Main?

**Comment by fako** [comment]
Volgens “gentlemans agreement”

**Comment by EvaWoertman** [comment]
Uit de testresultaten kwam er een probleem, dat ipv het PDF html code wordt getoond. Bijvoorbeeld:
https://client.publinova.acc.surf.zooma.cloud/product/5459909d-2248-4dc3-872d-527d50baa1f3 

Weet jij wat hier aan de hand is @fako ?

**Comment by fako** [comment]
Het materiaal is closed-access en er is dus geen bestand beschikbaar. Ik denk dat Zooma dan de url opent met een viewer, die dan de HTML toont van de website i.p.v. het (niet bestaande) bestand? De url wijst naar een overzichtspagina waar je meer informatie kunt vinden over een project: https://pure.buas.nl/en/publications/a-framework-for-biometric-playtesting-of-games-2
Files zijn daar niet te vinden, dus ik denk niet dat Zooma moet proberen iets te laten zien in de viewer in dit geval @EvaWoertman
