### ISSUE TITLE
Mapper maken voor Copyright

### ISSUE THREAD

**Issue by EvaWoertman** [nppo/ppp#27]
We moeten een mapper aanleveren voor de verschillende vormen van copyright, zodat het er op de frontend eenduidig uit ziet. Lijkt me handig om binnenkort bespreken.

'cc-by': 'Naamsvermelding',
            'cc-by-sa': 'Naamsvermelding-GelijkDelen',
            'cc-by-nc': 'Naamsvermelding-NietCommercieel',
            'cc-by-nc-sa': 'Naamsvermelding-NietCommercieel-GelijkDelen',
            'cc-by-nd': 'Naamsvermelding-GeenAfgeleideWerken',
            'cc-by-nc-nd': 'Naamsvermelding-NietCommercieel-GeenAfgeleideWerken',
            'cc-0': 'Publiek domein',
            'open-access': 'Open access',

**Comment by EvaWoertman** [comment]
@JohnMeurs  kan jij deze alvast aanvullen?
@fako  lijkt me handig om binnenkort te overleggen en dan deze mee te nemen

**Comment by JohnMeurs** [comment]
Is afhankelijk van : https://github.com/nppo/search-portal/issues/56

**Comment by fako** [comment]
Superseded by https://gitlab.surf.nl/publinova-group/project-main/-/issues/587
