### ISSUE TITLE
HVHL koppeling

### ISSUE THREAD

**Issue by fako** [nppo/ppp#4]
Scrape projecten? https://www.hvhl.nl/onderzoek/projecten.html
Mogelijke alternatieve weg is via Smartsheet: https://smartsheet.redoc.ly/#section/API-Basics/Assume-User

Voor producten wordt V-Smart gebruikt. Als het goed is is daar een OAI-PMH koppeling mee mogelijk. Snelle Google levert: https://github.com/caf3sua/vsmart-api

**Comment by JohnMeurs** [comment]
Richard geeft in mail dd  ( @martineteirlinck vult aan) dat er geen personen of projecten zijn

**Comment by fako** [comment]
Needs testing. Close when that's done

**Comment by fako** [comment]
Oeps, er zijn geen personen of projecten voor deze bron. Ga deze closen en meteen verwijderen uit project.
